### ISSUE TITLE
MAC M1 Max - Metal error matmul doesn't support BF16

### ISSUE THREAD

**Issue by oddpxl** [sensorial-systems/stable-diffusion#10]
Compiled this on a Macbook Pro M1 Max with 64Gb - I get Metal error matmul doesn't support BF16

**Comment by notdanilo** [comment]
Oh, I hardcoded it to BF16. Let me fix that

**Comment by notdanilo** [comment]
Let me just confirm. Are you talking about the cli?

**Comment by notdanilo** [comment]
stable-diffusion-cli 0.1.9 now uses F16 by default, not BF16.

In case you are talking about the example code, replace it with DType::F16. BF16 is NVidia only.

**Comment by notdanilo** [comment]
I closed the issue as it was likely fixed, but let me know if you still have any problem.

**Comment by oddpxl** [comment]
Yay that was fast - thanks :)

I now get this problem...

Building the unet.
Building the autoencoder.
Tensor[dims 2, 77, 2048; f16, metal:4294970041]
starting sampling
Error: Metal conv2d F16 not implemented

But this could well be on me as I'm new to Rust...  ..here's the code:

    let device = Device::new_metal(0)?;
    let weights = StableDiffusionWeights::new(StableDiffusionVersion::XL, DType::F32);
    let parameters = StableDiffusionParameters::new(weights, device, DType::F16)?;
    let stable_diffusion = StableDiffusion::new(parameters)?;
    let args = GenerationParameters::new("A green apple".to_string());
    let image = stable_diffusion.generate(args)?;
    image.save("output.png")?;

TOML
stable-diffusion = { version = "0.1.9", features = ["metal"], default-features = false }
candle = { package = "candle-core", version = "0.4.1" }
candle-metal-kernels = { version = "0.4.1" }

Best,
//O.

**Comment by notdanilo** [comment]
Try to run it with DType::F32. F16 might not exist for Metal. I don't know the API.

**Comment by oddpxl** [comment]
Yay ! It works !!!

Excellent - thank you

Now let's see if I can figure out how to load my own safetensor weights from civitai :)
